<?php
assert(defined('ROOT'));


/*****************************
         DEPENDENCIES
*****************************/

require_once __DIR__ . '/Data.php';
require_once __DIR__ . '/Kernel.php';


/*****************************
            CLASS
*****************************/

class Cache {

  /*****************************
              STATIC
  *****************************/

  /**
   * @param string $itinerary
   * The name of the folder containing the itinerary
   * for which we will generate an application cache file.
   *
   * @return int
   * The number of files to be downloaded for offline use.
   * The application cache file is directly written in the right directory.
   *
   * The new cache.manifest generated by the function is saved
   * under data/itineraries/$itinerary/cache-$lang-.manifest.
   * where $lang is the language code.
   *
   * We indeed need to generate a cache manifest for a specific language
   * otherwise, if a user downloads an itinerary and then switches language,
   * he will get the itinerary in the former language and not the new one.
   */
  public static function generate($itinerary) {
    $kernel = Kernel::getInstance();
    $config = $kernel->getConfig();
    $root = $config['root'];

    $data = Data::load("itineraries/$itinerary/contents");
    $numFiles = 0;

    $contents = "CACHE MANIFEST\n";

    $defaultCache = Data::load("cache");

    $cached = $defaultCache['cache'];

    // cached pages: list of itinerary steps
    $cached[] = "itineraries/$itinerary/steps";

    foreach($data['files'] as $file) {
      $cached[] = "img/itineraries/$file";
    }

    foreach($data['steps'] as $step) {
      $cached[] = "itineraries/$itinerary/$step";
    }

    $contents .= "\nCACHE:\n";
    foreach($cached as $cachedLine) {
      $contents .= "  $root" . "$cachedLine\n";
      $numFiles++;
    }

    $contents .= "\nFALLBACK:\n";
    $contents .= "  / $root" . "offline\n";
    $numFiles++; // the fallback route counts as a file to be cached

    $contents .= "\nNETWORK:\n  *\n\n";

    file_put_contents("data/itineraries/$itinerary/cache-" . $kernel->getI18N()->getPreferredLanguage() . ".manifest", $contents);

    return $numFiles;
  }

}

